# Generated by Django 5.2.3 on 2025-07-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='categoria',
            field=models.CharField(choices=[('ALIMENTACAO', 'Alimentação'), ('TRANSPORTE', 'Transporte'), ('MORADIA', 'Moradia'), ('LAZER', 'Lazer'), ('SAUDE', 'Saúde'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20),
        ),
    ]
